### ISSUE TITLE
Board definition files missing

### ISSUE THREAD

**Issue by cairo-caplan** [CoXlabInc/Nol.A-AcSip-S76G-Example#1]
Hello,

I tried to build the basic project but it seems that there are files missing on Nol.A setup as it shows below in a compilation build:

```
[Nol.A] Application project path: C:\Users\my_user\Downloads\Nol.A-AcSip-S76G-Example-master\Basic
[Nol.A] Target device: acsip-s76g
[Nol.A] Target port: None
[Nol.A] Build the application project.
[Nol.A] Ver: 0.10.51
C:\Users\my_user\.atom\nola-sdk\make\Makefile:141: C:/Users/my_user/.atom/nola-sdk/make/../acsip-s76g/Makefile: No such file or directory
make: *** No rule to make target `C:/Users/my_user/.atom/nola-sdk/make/../acsip-s76g/Makefile'.  Stop.

[Nol.A] Building the application project failed.
```

**Comment by jsjeong** [comment]
I'm sorry for too late response.

Currently, supporting Acsip's S76G SiP is aborted due to some business problem.
I think using the SDK from https://techship.com/products/acsip-s76gxb-developer-kit will be helpful to you.

Thank you.
